let contacts = [
  {
    id: 1,
    first_name: "Alexina",
    last_name: "Loxston",
    email: "aloxston0@auda.org.au",
    gender: "Male",
    location: "Nam Kliang",
    age: "3/31/2021",
  },
  {
    id: 2,
    first_name: "Joanna",
    last_name: "Pellman",
    email: "jpellman1@friendfeed.com",
    gender: "Genderfluid",
    location: "Sykiés",
    age: "1/7/2021",
  },
  {
    id: 3,
    first_name: "Serena",
    last_name: "Hess",
    email: "shess2@posterous.com",
    gender: "Non-binary",
    location: "Salto",
    age: "5/6/2020",
  },
  {
    id: 4,
    first_name: "Wanids",
    last_name: "Farre",
    email: "wfarre3@telegraph.co.uk",
    gender: "Female",
    location: "Vantaa",
    age: "12/7/2020",
  },
  {
    id: 5,
    first_name: "Tull",
    last_name: "Keelinge",
    email: "tkeelinge4@smugmug.com",
    gender: "Genderqueer",
    location: "Al Marj",
    age: "2/8/2021",
  },
  {
    id: 6,
    first_name: "Chandler",
    last_name: "Quadrio",
    email: "cquadrio5@bigcartel.com",
    gender: "Genderfluid",
    location: "Yiqian",
    age: "11/25/2020",
  },
  {
    id: 7,
    first_name: "Farica",
    last_name: "Goodlad",
    email: "fgoodlad6@twitter.com",
    gender: "Female",
    location: "Datagon",
    age: "1/22/2021",
  },
  {
    id: 8,
    first_name: "Datha",
    last_name: "Dongate",
    email: "ddongate7@angelfire.com",
    gender: "Male",
    location: "Palmas De Gran Canaria, Las",
    age: "8/4/2020",
  },
  {
    id: 9,
    first_name: "Jamie",
    last_name: "Ree",
    email: "jree8@harvard.edu",
    gender: "Genderfluid",
    location: "General Vedia",
    age: "7/14/2020",
  },
  {
    id: 10,
    first_name: "Marney",
    last_name: "Hannant",
    email: "mhannant9@pcworld.com",
    gender: "Polygender",
    location: "Tegalgunung",
    age: "4/6/2021",
  },
  {
    id: 11,
    first_name: "Grenville",
    last_name: "Slowley",
    email: "gslowleya@jigsy.com",
    gender: "Agender",
    location: "Genang",
    age: "6/25/2020",
  },
  {
    id: 12,
    first_name: "Averil",
    last_name: "Mulleary",
    email: "amullearyb@webmd.com",
    gender: "Non-binary",
    location: "Dalongzhan",
    age: "6/25/2020",
  },
  {
    id: 13,
    first_name: "Wilbert",
    last_name: "Hadley",
    email: "whadleyc@dell.com",
    gender: "Polygender",
    location: "Pensacola",
    age: "5/15/2020",
  },
  {
    id: 14,
    first_name: "Nady",
    last_name: "Salazar",
    email: "nsalazard@bizjournals.com",
    gender: "Male",
    location: "Karlstad",
    age: "2/2/2021",
  },
  {
    id: 15,
    first_name: "Lorna",
    last_name: "Redd",
    email: "lredde@pinterest.com",
    gender: "Male",
    location: "Aristóbulo del Valle",
    age: "6/20/2020",
  },
  {
    id: 16,
    first_name: "Bronnie",
    last_name: "Mellanby",
    email: "bmellanbyf@mtv.com",
    gender: "Genderfluid",
    location: "Viana do Castelo",
    age: "3/6/2021",
  },
  {
    id: 17,
    first_name: "Nealson",
    last_name: "Loton",
    email: "nlotong@sciencedaily.com",
    gender: "Bigender",
    location: "Ban Takhun",
    age: "1/1/2021",
  },
  {
    id: 18,
    first_name: "Alphard",
    last_name: "Stranio",
    email: "astranioh@gravatar.com",
    gender: "Polygender",
    location: "Bang Racham",
    age: "4/7/2021",
  },
  {
    id: 19,
    first_name: "Gaylor",
    last_name: "Josskoviz",
    email: "gjosskovizi@cornell.edu",
    gender: "Agender",
    location: "Shidu",
    age: "10/9/2020",
  },
  {
    id: 20,
    first_name: "Daveta",
    last_name: "Linde",
    email: "dlindej@ezinearticles.com",
    gender: "Male",
    location: "Limache",
    age: "3/5/2021",
  },
];

let result = contacts.map((contact) => {
  return contact.gender.toLocaleLowerCase();
});

console.log(result);
